### ISSUE TITLE
Supporting micrometer metrics thru MicrometerMetricsCollector

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-rabbitmq-client#84] opened 2022-01-28 09:48 UTC
Hello. Great extension :)

https://github.com/rabbitmq/rabbitmq-java-client/blob/main/src/main/java/com/rabbitmq/client/impl/MicrometerMetricsCollector.java exists in AMQP client

Would it be possible for your extension to plug and use this collector ? To expose all the private final counters and atomics

To get metrics in Grafana, Datadog, JMX or other tool

I believe Erin from https://github.com/quarkiverse/quarkus-micrometer-registry is the expert here.

Thanks !

**Comment by bpasson** [comment] 2022-01-29 13:31
Thanks for taking the time to create this issue. I'm sure the metrics can be exposed. You also registered issue #72. Thats has been put on the 0.5.0 milestone. Is this requesting the same feature?

It has been a busy time and I have not been able to put a lot of time into work for the 0.5.0 milestone release.

**Comment by laurentperez** [comment] 2022-01-29 18:53
Wow I forgot I opened https://github.com/quarkiverse/quarkus-rabbitmq-client/issues/72 . Indeed this is a duplicate, sorry

**Comment by bpasson** [comment] 2022-02-02 19:24
Closing as duplicate of #72.

**Closed by bpasson** 2022-02-02 19:24 UTC
