### ISSUE TITLE
topologyRecovery does not fire

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-rabbitmq-client#85] opened 2022-02-05 10:11 UTC
Hello

This is an evil one, I could do a PR but I'm not sure on how to fix this sanely so I'm asking here for ideas. I've looked into SR-MQ, Camel or Spring AMQP commits for a similar one but could not find an equivalent

In https://github.com/quarkiverse/quarkus-rabbitmq-client/blob/master/runtime/src/main/java/io/quarkiverse/rabbitmqclient/RabbitMQClientConfig.java#L136 is set to "true"

But it all boils down to the nasty https://github.com/rabbitmq/rabbitmq-java-client/commit/e9b642f7e34499b67928d00c4b868d5e9228e34f#diff-3ee7482ebddb8471bf938e29cb3b8d0704c94e0cf94fe6a67593149b99f38c69R190

Where Boolean.getBoolean will resolve to a system property. So unless you do something fancy like -Dtrue=true in jvm args (which, we did), topology will not work

Really not sure on how to fix this without some very ugly patch. Also if others like us did the true=true trick, well it will break in production if changed.

Maybe hardcoding it to true thru a CF setter is enough, together with topology filters when people do not want to reconstruct the whole topology in corner cases ? But given the closed world of native graal maybe the System prop should be taken care of too.

Regards

**Comment by laurentperez** [comment] 2022-02-05 10:17
By filter I meant https://github.com/rabbitmq/rabbitmq-java-client/commit/a89dd9aaa47f9bfbb9066a00906996506d6f675e

**Comment by bpasson** [comment] 2022-02-05 11:39
@laurentperez Interesting. I'll have to take a deeper look at.

**Comment by bpasson** [comment] 2022-02-05 11:56
It is a bug in the official RabbitMQ client. I really don't want to try and work around it. Probably best to send a PR to fix the root cause. Then I can update the client version here. Since you found it, do you want to send the PR to take credits or want me to do it?

**Comment by laurentperez** [comment] 2022-02-05 13:31
I'll PR it in the official client so that you can update.

**Comment by bpasson** [comment] 2022-02-05 17:44
Very good. When a new client is available I'll update.

**Comment by bpasson** [comment] 2022-02-10 20:11
@laurentperez this will be in the next release.

**Closed** 2022-02-11 21:29 UTC
